const EMOJI_MAP: Record<string, string> = {
  hello: "👋",
  hola: "👋",
  goodbye: "👋",
  adiós: "👋",
  please: "🙏",
  "por favor": "🙏",
  thanks: "🙌",
  gracias: "🙌",
  book: "📚",
  libro: "📚",
  teacher: "👩‍🏫",
  profesor: "👩‍🏫",
  student: "🎒",
  estudiante: "🎒",
  family: "👨‍👩‍👧",
  familia: "👨‍👩‍👧",
  friend: "🤝",
  amigo: "🤝",
  school: "🏫",
  escuela: "🏫",
  water: "💧",
  agua: "💧",
  food: "🍽️",
  comida: "🍽️",
  milk: "🥛",
  leche: "🥛",
  red: "🔴",
  rojo: "🔴",
  blue: "🔵",
  azul: "🔵",
  green: "🟢",
  verde: "🟢",
  cat: "🐱",
  gato: "🐱",
  dog: "🐶",
  perro: "🐶",
  bird: "🐦",
  pájaro: "🐦",
  mother: "👩",
  madre: "👩",
  father: "👨",
  padre: "👨",
  sister: "👧",
  hermana: "👧",
  house: "🏠",
  casa: "🏠",
  room: "🛏️",
  habitación: "🛏️",
  door: "🚪",
  puerta: "🚪",
  sun: "☀️",
  sol: "☀️",
  rain: "🌧️",
  lluvia: "🌧️",
  wind: "💨",
  viento: "💨",
  happy: "😊",
  feliz: "😊",
  sad: "😢",
  triste: "😢",
  tired: "😴",
  cansado: "😴",
  morning: "🌅",
  mañana: "🌅",
  night: "🌙",
  noche: "🌙",
  today: "📅",
  hoy: "📅",
  apple: "🍎",
  manzana: "🍎",
  bread: "🍞",
  pan: "🍞",
  rice: "🍚",
  arroz: "🍚",
  car: "🚗",
  carro: "🚗",
  bus: "🚌",
  autobús: "🚌",
  bike: "🚲",
  bicicleta: "🚲",
  one: "1️⃣",
  uno: "1️⃣",
  two: "2️⃣",
  dos: "2️⃣",
  three: "3️⃣",
  tres: "3️⃣",
  run: "🏃",
  correr: "🏃",
  walk: "🚶",
  caminar: "🚶",
  play: "⚽",
  jugar: "⚽",
  read: "📖",
  leer: "📖",
  write: "✍️",
  escribir: "✍️",
  listen: "👂",
  escuchar: "👂",
};

export const getOptionEmoji = (text: string): string => {
  const key = text.trim().toLowerCase();
  return EMOJI_MAP[key] ?? "✨";
};

export const SEGMENT_MASCOT: Record<string, { emoji: string; title: string; hint: string }> = {
  presentation: {
    emoji: "🧠",
    title: "¡Descubre!",
    hint: "Lee el objetivo y elige la respuesta correcta",
  },
  practice: {
    emoji: "🎯",
    title: "¡Practica!",
    hint: "Demuestra lo que aprendiste",
  },
  use: {
    emoji: "🚀",
    title: "¡Úsalo!",
    hint: "Lee la pista en español («azul», «gato»…) y completa la frase en inglés",
  },
};
