import {
  COMPETENCY_1_LESSON_TERMS,
  COMPETENCY_1_WORD_BANK,
  firstGradeWorkbookBlock,
  isFirstGradeLesson,
  lookupCompetency1Term,
} from "./competency-1-curriculum";

export type VocabItem = { term: string; meaning: string };

export {
  COMPETENCY_1_WORD_BANK,
  auditCompetency1WordBank,
  FIRST_GRADE_LESSONS,
  FIRST_GRADE_COMPETENCIES,
  FIRST_GRADE_COMPETENCY_TITLE,
  firstGradeWorkbookBlock,
  isFirstGradeLesson,
} from "./competency-1-curriculum";

export type CompetencyTheme = {
  title: string;
  words: VocabItem[];
};

const parseWords = (entries: string[]): VocabItem[] =>
  entries.map((entry) => {
    const sep = entry.indexOf(":");
    return {
      term: entry.slice(0, sep),
      meaning: entry.slice(sep + 1),
    };
  });

/** Competencia 1 usa el word bank completo del workbook MOA A1C1. */
const COMPETENCY_1_WORDS = COMPETENCY_1_WORD_BANK;

/** 16 temas × 24 palabras = 384 términos únicos (8 lecciones × 3 palabras por tema). */
export const COMPETENCY_THEMES: CompetencyTheme[] = [
  {
    title: "Información personal y familia",
    words: COMPETENCY_1_WORDS,
  },
  {
    title: "Escuela",
    words: parseWords([
      "book:libro",
      "teacher:profesor",
      "student:estudiante",
      "pencil:lápiz",
      "desk:escritorio",
      "class:clase",
      "lesson:lección",
      "homework:tarea",
      "read:leer",
      "write:escribir",
      "learn:aprender",
      "study:estudiar",
      "question:pregunta",
      "bell:timbre",
      "paper:papel",
      "pen:pluma",
      "eraser:borrador",
      "bag:mochila",
      "ruler:regla",
      "chair:silla",
      "library:biblioteca",
      "test:examen",
      "grade:nota",
      "notebook:cuaderno",
    ]),
  },
  {
    title: "Familia",
    words: parseWords([
      "mother:madre",
      "father:padre",
      "sister:hermana",
      "brother:hermano",
      "baby:bebé",
      "grandma:abuela",
      "grandpa:abuelo",
      "family:familia",
      "son:hijo",
      "daughter:hija",
      "uncle:tío",
      "aunt:tía",
      "cousin:primo",
      "parents:padres",
      "child:niño",
      "kids:niños",
      "husband:esposo",
      "wife:esposa",
      "love:amor",
      "home:hogar",
      "together:juntos",
      "hug:abrazo",
      "care:cuidado",
      "niece:sobrina",
    ]),
  },
  {
    title: "Comida",
    words: parseWords([
      "water:agua",
      "food:comida",
      "milk:leche",
      "bread:pan",
      "rice:arroz",
      "soup:sopa",
      "egg:huevo",
      "cheese:queso",
      "meat:carne",
      "fish:pescado",
      "salt:sal",
      "sugar:azúcar",
      "plate:plato",
      "cup:taza",
      "fork:tenedor",
      "spoon:cuchara",
      "knife:cuchillo",
      "breakfast:desayuno",
      "lunch:almuerzo",
      "dinner:cena",
      "hungry:hambriento",
      "thirsty:sediento",
      "cook:cocinar",
      "eat:comer",
    ]),
  },
  {
    title: "Colores y formas",
    words: parseWords([
      "red:rojo",
      "blue:azul",
      "green:verde",
      "yellow:amarillo",
      "black:negro",
      "white:blanco",
      "orange:naranja",
      "purple:morado",
      "pink:rosa",
      "brown:marrón",
      "gray:gris",
      "gold:dorado",
      "silver:plateado",
      "color:color",
      "bright:brillante",
      "dark:oscuro",
      "light:claro",
      "round:redondo",
      "square:cuadrado",
      "big:grande",
      "small:pequeño",
      "long:largo",
      "short:corto",
      "tall:alto",
    ]),
  },
  {
    title: "Animales",
    words: parseWords([
      "cat:gato",
      "dog:perro",
      "bird:pájaro",
      "goat:cabra",
      "cow:vaca",
      "pig:cerdo",
      "horse:caballo",
      "sheep:oveja",
      "duck:pato",
      "chicken:gallina",
      "rabbit:conejo",
      "mouse:ratón",
      "lion:león",
      "bear:oso",
      "frog:rana",
      "snake:serpiente",
      "bee:abeja",
      "butterfly:mariposa",
      "elephant:elefante",
      "monkey:mono",
      "zoo:zoológico",
      "pet:mascota",
      "tail:cola",
      "paw:pata",
    ]),
  },
  {
    title: "Cuerpo",
    words: parseWords([
      "head:cabeza",
      "hair:cabello",
      "eye:ojo",
      "ear:oreja",
      "nose:nariz",
      "mouth:boca",
      "tooth:diente",
      "hand:mano",
      "finger:dedo",
      "arm:brazo",
      "leg:pierna",
      "foot:pie",
      "knee:rodilla",
      "back:espalda",
      "neck:cuello",
      "face:cara",
      "heart:corazón",
      "body:cuerpo",
      "sick:enfermo",
      "hurt:doler",
      "wink:guiño",
      "brush:cepillar",
      "lip:labio",
      "tear:lágrima",
    ]),
  },
  {
    title: "Ropa",
    words: parseWords([
      "shirt:camisa",
      "pants:pantalón",
      "dress:vestido",
      "shoes:zapatos",
      "socks:calcetines",
      "hat:sombrero",
      "coat:abrigo",
      "jacket:chaqueta",
      "skirt:falda",
      "sweater:suéter",
      "gloves:guantes",
      "scarf:bufanda",
      "boots:botas",
      "tie:corbata",
      "belt:cinturón",
      "pocket:bolsillo",
      "button:botón",
      "wear:usar",
      "tag:etiqueta",
      "fold:doblar",
      "dirty:sucio",
      "new:nuevo",
      "old:viejo",
      "size:talla",
    ]),
  },
  {
    title: "Casa",
    words: parseWords([
      "house:casa",
      "room:habitación",
      "door:puerta",
      "window:ventana",
      "bed:cama",
      "table:mesa",
      "kitchen:cocina",
      "bathroom:baño",
      "floor:piso",
      "roof:techo",
      "wall:pared",
      "garden:jardín",
      "lamp:lámpara",
      "key:llave",
      "stairs:escaleras",
      "box:caja",
      "closet:armario",
      "sofa:sofá",
      "clock:reloj",
      "phone:teléfono",
      "live:vivir",
      "tidy:ordenar",
      "open:abrir",
      "close:cerrar",
    ]),
  },
  {
    title: "Clima",
    words: parseWords([
      "sun:sol",
      "rain:lluvia",
      "wind:viento",
      "snow:nieve",
      "cloud:nube",
      "storm:tormenta",
      "hot:caliente",
      "cold:frío",
      "warm:tibio",
      "cool:fresco",
      "weather:clima",
      "sky:cielo",
      "umbrella:paraguas",
      "spring:primavera",
      "summer:verano",
      "autumn:otoño",
      "winter:invierno",
      "fog:niebla",
      "dry:seco",
      "wet:mojado",
      "sunny:soleado",
      "cloudy:nublado",
      "windy:ventoso",
      "stormy:tormentoso",
    ]),
  },
  {
    title: "Emociones",
    words: parseWords([
      "happy:feliz",
      "sad:triste",
      "tired:cansado",
      "angry:enojado",
      "scared:asustado",
      "excited:emocionado",
      "bored:aburrido",
      "surprised:sorprendido",
      "proud:orgulloso",
      "shy:tímido",
      "calm:tranquilo",
      "worried:preocupado",
      "brave:valiente",
      "kind:amable",
      "funny:gracioso",
      "lonely:solitario",
      "joy:alegría",
      "hope:esperanza",
      "peace:paz",
      "laugh:risa",
      "cry:llorar",
      "feel:sentir",
      "mood:ánimo",
      "grin:sonreír",
    ]),
  },
  {
    title: "Tiempo",
    words: parseWords([
      "today:hoy",
      "tomorrow:mañana",
      "yesterday:ayer",
      "dawn:amanecer",
      "dusk:atardecer",
      "week:semana",
      "month:mes",
      "year:año",
      "hour:hora",
      "minute:minuto",
      "second:segundo",
      "now:ahora",
      "later:después",
      "early:temprano",
      "late:tarde",
      "always:siempre",
      "never:nunca",
      "often:a menudo",
      "sometimes:a veces",
      "soon:pronto",
      "past:pasado",
      "future:futuro",
      "weekday:día hábil",
      "weekend:fin de semana",
    ]),
  },
  {
    title: "Frutas y snacks",
    words: parseWords([
      "apple:manzana",
      "banana:plátano",
      "grape:uva",
      "lemon:limón",
      "peach:durazno",
      "pear:pera",
      "cherry:cereza",
      "strawberry:fresa",
      "watermelon:sandía",
      "pineapple:piña",
      "mango:mango",
      "coconut:coco",
      "avocado:aguacate",
      "melon:melón",
      "berry:baya",
      "fruit:fruta",
      "juice:jugo",
      "sweet:dulce",
      "sour:ácido",
      "ripe:maduro",
      "fresh:fresco",
      "slice:rebanada",
      "peel:cáscara",
      "snack:botana",
    ]),
  },
  {
    title: "Transporte",
    words: parseWords([
      "car:carro",
      "bus:autobús",
      "bike:bicicleta",
      "train:tren",
      "plane:avión",
      "boat:barco",
      "ship:barco grande",
      "truck:camión",
      "taxi:taxi",
      "subway:metro",
      "road:camino",
      "street:calle",
      "wheel:rueda",
      "seat:asiento",
      "drive:manejar",
      "ride:montar",
      "stop:parar",
      "fast:rápido",
      "slow:lento",
      "honk:bocina",
      "bridge:puente",
      "park:estacionar",
      "gasoline:gasolina",
      "ticket:boleto",
    ]),
  },
  {
    title: "Naturaleza",
    words: parseWords([
      "tree:árbol",
      "flower:flor",
      "grass:pasto",
      "leaf:hoja",
      "rock:roca",
      "river:río",
      "lake:lago",
      "mountain:montaña",
      "hill:colina",
      "forest:bosque",
      "beach:playa",
      "sand:arena",
      "stone:piedra",
      "plant:planta",
      "seed:semilla",
      "grow:crecer",
      "earth:tierra",
      "star:estrella",
      "moon:luna",
      "planet:planeta",
      "island:isla",
      "ocean:océano",
      "field:campo",
      "nature:naturaleza",
    ]),
  },
  {
    title: "Acciones",
    words: parseWords([
      "run:correr",
      "walk:caminar",
      "play:jugar",
      "jump:saltar",
      "swim:nadar",
      "climb:escalar",
      "dance:bailar",
      "sing:cantar",
      "draw:dibujar",
      "bake:hornear",
      "sweep:barrear",
      "wipe:secar",
      "clap:aplauso",
      "lock:cerrar con llave",
      "push:empujar",
      "pull:jalar",
      "throw:lanzar",
      "catch:atrapar",
      "kick:patear",
      "sit:sentarse",
      "stand:pararse",
      "sleep:dormir",
      "wake:despertar",
      "shout:gritar",
    ]),
  },
];

export const THEME_COUNT = COMPETENCY_THEMES.length;
export const WORDS_PER_THEME = 24;
export const LESSONS_PER_THEME = 8;
export const WORDS_PER_LESSON = 3;

/** Reparte vocabulario temático: 16 temas × 8 lecciones × 3 palabras únicas. */
export const getLessonPlan = (idLeccion: number) => {
  const slot = idLeccion - 1;
  const rawThemeIndex = Math.floor(slot / LESSONS_PER_THEME) % THEME_COUNT;
  const lessonSlot = slot % LESSONS_PER_THEME;
  const focusIndex = lessonSlot % WORDS_PER_LESSON;
  const firstGrade = isFirstGradeLesson(idLeccion);
  const themeIndex = firstGrade ? 0 : rawThemeIndex;
  const theme = firstGrade ? COMPETENCY_THEMES[0] : COMPETENCY_THEMES[rawThemeIndex];
  const competencyIndex = Math.floor(slot / LESSONS_PER_THEME);

  let set: VocabItem[];
  if (firstGrade) {
    const block = firstGradeWorkbookBlock(idLeccion);
    const terms = COMPETENCY_1_LESSON_TERMS[block];
    set = terms.map((term) => {
      const item = lookupCompetency1Term(term);
      if (!item) {
        throw new Error(
          `1.er grado (lección ${idLeccion}): término "${term}" no encontrado en word bank`,
        );
      }
      return item;
    });
  } else {
    const wordStart = lessonSlot * WORDS_PER_LESSON;
    set = theme.words.slice(wordStart, wordStart + WORDS_PER_LESSON);
  }

  const focus = set[focusIndex];
  const variant = firstGrade
    ? (Math.floor(slot / WORDS_PER_LESSON) + competencyIndex) % 3
    : Math.floor(slot / WORDS_PER_LESSON) % 3;
  return {
    slot,
    themeIndex,
    lessonSlot,
    focusIndex,
    variant,
    theme,
    set,
    focus,
  };
};
