import { EXTRA_EMOJI } from "./lesson-emojis-extra";

const EMOJI_MAP: Record<string, string> = {
  hello: "👋",
  hola: "👋",
  please: "🙏",
  "por favor": "🙏",
  thanks: "🙌",
  gracias: "🙌",
  book: "📚",
  libro: "📚",
  teacher: "👩‍🏫",
  profesor: "👩‍🏫",
  student: "🎒",
  estudiante: "🎒",
  family: "👨‍👩‍👧",
  familia: "👨‍👩‍👧",
  friend: "🤝",
  amigo: "🤝",
  school: "🏫",
  escuela: "🏫",
  water: "💧",
  agua: "💧",
  food: "🍽️",
  comida: "🍽️",
  milk: "🥛",
  leche: "🥛",
  red: "🔴",
  rojo: "🔴",
  blue: "🔵",
  azul: "🔵",
  green: "🟢",
  verde: "🟢",
  cat: "🐱",
  gato: "🐱",
  dog: "🐶",
  perro: "🐶",
  bird: "🐦",
  pájaro: "🐦",
  mother: "👩",
  madre: "👩",
  father: "👨",
  padre: "👨",
  sister: "👧",
  hermana: "👧",
  house: "🏠",
  casa: "🏠",
  room: "🛏️",
  habitación: "🛏️",
  door: "🚪",
  puerta: "🚪",
  sun: "☀️",
  sol: "☀️",
  rain: "🌧️",
  lluvia: "🌧️",
  wind: "💨",
  viento: "💨",
  happy: "😊",
  feliz: "😊",
  sad: "😢",
  triste: "😢",
  tired: "😴",
  cansado: "😴",
  morning: "🌅",
  mañana: "🌅",
  night: "🌙",
  noche: "🌙",
  today: "📅",
  hoy: "📅",
  apple: "🍎",
  manzana: "🍎",
  bread: "🍞",
  pan: "🍞",
  rice: "🍚",
  arroz: "🍚",
  car: "🚗",
  carro: "🚗",
  bus: "🚌",
  autobús: "🚌",
  bike: "🚲",
  bicicleta: "🚲",
  one: "1️⃣",
  uno: "1️⃣",
  two: "2️⃣",
  dos: "2️⃣",
  three: "3️⃣",
  tres: "3️⃣",
  run: "🏃",
  correr: "🏃",
  walk: "🚶",
  caminar: "🚶",
  play: "⚽",
  jugar: "⚽",
  read: "📖",
  leer: "📖",
  write: "✍️",
  escribir: "✍️",
  listen: "👂",
  escuchar: "👂",
  ...EXTRA_EMOJI,
  lesson: "📒",
  lección: "📒",
  goodbye: "✌️",
  adiós: "✌️",
  hi: "🙂",
  bye: "✌️",
};

export const getOptionEmoji = (text: string): string => {
  const key = text.trim().toLowerCase();
  return EMOJI_MAP[key] ?? "✨";
};

/** Emojis alternativos cuando dos opciones de la misma pregunta comparten icono. */
const TERM_EMOJI_ALTS: Record<string, string[]> = {
  lesson: ["📒", "📖", "🎓"],
  lección: ["📒", "📖", "🎓"],
  read: ["📖", "📕", "👓"],
  leer: ["📖", "📕", "👓"],
  hello: ["👋", "🙂"],
  hola: ["👋", "🙂"],
  goodbye: ["✌️", "👋"],
  adiós: ["✌️", "👋"],
  hi: ["🙂", "👋"],
  bye: ["✌️", "👋"],
  good: ["👍", "✅"],
  bueno: ["👍", "✅"],
  well: ["💪", "👍"],
  cousin: ["🧑", "👦", "🧒"],
  primo: ["🧑", "👦", "🧒"],
  child: ["🧒", "👶"],
  niño: ["🧒", "👶"],
  kid: ["👶", "🧒"],
  son: ["👦", "🧒"],
  hijo: ["👦", "🧒"],
  brother: ["👦", "🧔"],
  hermano: ["👦", "🧔"],
  pet: ["🐾", "🐶"],
  mascota: ["🐾", "🐶"],
  tail: ["🦴", "🐕"],
  cola: ["🦴", "🐕"],
  paw: ["🐾", "🐱"],
  pata: ["🐾", "🐱"],
  coat: ["🧥", "🦺"],
  abrigo: ["🧥", "🦺"],
  jacket: ["🦺", "🧥"],
  chaqueta: ["🦺", "🧥"],
  room: ["🚪", "🛏️"],
  habitación: ["🚪", "🛏️"],
  bed: ["🛏️", "💤"],
  cama: ["🛏️", "💤"],
  live: ["🏡", "🏠"],
  roof: ["🏚️", "🏠"],
  techo: ["🏚️", "🏠"],
  river: ["🌊", "🏞️"],
  río: ["🌊", "🏞️"],
  lake: ["💧", "🏞️"],
  lago: ["💧", "🏞️"],
  mountain: ["⛰️", "🏔️"],
  montaña: ["⛰️", "🏔️"],
  hill: ["🌄", "⛰️"],
  colina: ["🌄", "⛰️"],
  beach: ["🏖️", "🌊"],
  playa: ["🏖️", "🌊"],
  sand: ["🏝️", "🏖️"],
  arena: ["🏝️", "🏖️"],
  plant: ["🪴", "🌱"],
  planta: ["🪴", "🌱"],
  seed: ["🌰", "🌱"],
  semilla: ["🌰", "🌱"],
  clean: ["🧹", "🧼"],
  limpiar: ["🧹", "🧼"],
  wash: ["🫧", "🧼"],
  lavar: ["🫧", "🧼"],
  cook: ["👨‍🍳", "🍳"],
  cocinar: ["👨‍🍳", "🍳"],
  book: ["📚", "📖", "📕"],
  libro: ["📚", "📖", "📕"],
  study: ["📚", "🎓", "✏️"],
  estudiar: ["📚", "🎓", "✏️"],
  library: ["🏛️", "📚", "📖"],
  biblioteca: ["🏛️", "📚", "📖"],
  ruler: ["📏", "📐", "✏️"],
  regla: ["📏", "📐", "✏️"],
  bell: ["🔔", "🔕", "🛎️"],
  timbre: ["🔔", "🔕", "🛎️"],
  chair: ["🪑", "💺"],
  silla: ["🪑", "💺"],
  desk: ["🗄️", "🖥️", "🪑"],
  escritorio: ["🗄️", "🖥️", "🪑"],
  table: ["🍽️", "🔲", "🪑"],
  mesa: ["🍽️", "🔲", "🪑"],
  pencil: ["✏️", "✒️", "🖊️"],
  lápiz: ["✏️", "✒️", "🖊️"],
  pen: ["🖊️", "✒️", "✏️"],
  pluma: ["🖊️", "✒️", "✏️"],
  paper: ["📄", "📃", "📝"],
  papel: ["📄", "📃", "📝"],
  homework: ["📝", "📋", "📓"],
  tarea: ["📝", "📋", "📓"],
  test: ["📝", "✅", "📄"],
  examen: ["📝", "✅", "📄"],
  notebook: ["📓", "📔", "📒"],
  cuaderno: ["📓", "📔", "📒"],
  gift: ["🎁", "🎀", "💝"],
  regalo: ["🎁", "🎀", "💝"],
  tag: ["🏷️", "📌", "🔖"],
  etiqueta: ["🏷️", "📌", "🔖"],
  honk: ["📯", "🚗", "🔊"],
  bocina: ["📯", "🚗", "🔊"],
  clap: ["👏", "🙌", "✋"],
  aplauso: ["👏", "🙌", "✋"],
  glad: ["😊", "😁", "🙂"],
  fine: ["👌", "👍", "✅"],
  nice: ["😊", "🌟", "💛"],
  face: ["😊", "🙂", "😀"],
  happy: ["😊", "😄", "🙂"],
  daughter: ["👧", "👩", "🧒"],
  sister: ["👧", "👩", "🧒"],
  home: ["🏠", "🏡", "🏘️"],
  house: ["🏠", "🏡", "🏘️"],
  dinner: ["🍽️", "🍲", "🥘"],
  food: ["🍽️", "🍲", "🥗"],
  plate: ["🍽️", "🥘", "🍛"],
};

const FALLBACK_EMOJI_POOL = [
  "⭐",
  "🌟",
  "✨",
  "💫",
  "🎯",
  "🎨",
  "🎵",
  "🎈",
  "🍀",
  "🔷",
  "🔶",
  "💎",
  "🌈",
  "🔔",
  "📌",
];

/** Una emoji distinta por opción (evita confundir Lesson/Read con el mismo 📖). */
export const getDistinctOptionEmojisForChoices = (
  options: string[],
): string[] => {
  const used = new Set<string>();
  return options.map((option) => {
    const key = option.trim().toLowerCase();
    const candidates = [
      getOptionEmoji(option),
      ...(TERM_EMOJI_ALTS[key] ?? []),
      ...FALLBACK_EMOJI_POOL,
    ];
    const emoji = candidates.find((item) => !used.has(item)) ?? "✨";
    used.add(emoji);
    return emoji;
  });
};

/** Asigna emojis únicos a cada opción de un juego (imagen, memoria, parejas). */
export const applyDistinctOptionEmojis = <T extends { term: string; emoji: string }>(
  items: T[],
): T[] => {
  const emojis = getDistinctOptionEmojisForChoices(items.map((item) => item.term));
  return items.map((item, index) => ({ ...item, emoji: emojis[index] }));
};

export const SEGMENT_MASCOT: Record<
  string,
  { emoji: string; title: string; hint: string; label: string }
> = {
  presentation: {
    emoji: "📖",
    label: "Aprende",
    title: "¡Descubre!",
    hint: "Conoce las palabras nuevas y su significado",
  },
  practice: {
    emoji: "🎮",
    label: "Juega",
    title: "¡Practica!",
    hint: "Juega y demuestra lo que aprendiste",
  },
  use: {
    emoji: "💬",
    label: "Usa",
    title: "¡Úsalo!",
    hint: "Completa frases en inglés con las palabras",
  },
};
